# -*- coding: utf-8 -*-
"""KNN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p90EngR7skAHqdMPNlTz7xUU3Gan4k1S
"""

import pandas as pd
import pickle

df = pd.read_csv('upscale.csv')

df.head(10)

df = df.drop(columns="Hybridization REF")
from sklearn.model_selection import train_test_split
training_set, test_set = train_test_split(df, test_size = 0.2, random_state = 1)

X_train = training_set.iloc[:,0:21].values
Y_train = training_set.iloc[:,21].values

X_test = test_set.iloc[:,0:21].values
Y_test = test_set.iloc[:,21].values

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=15)
knn.fit(X_train,Y_train)

y_pred = knn.predict(X_test)

from sklearn.metrics import accuracy_score
accuracy_score(Y_test,y_pred)

from sklearn.metrics import precision_score, recall_score, f1_score
precision = precision_score(Y_test,y_pred)
print(precision)

recall_score(Y_test, y_pred)

f1_score(Y_test, y_pred)

#serialization and de-serialization
pickle.dump(knn, open('model1.pkl','wb'))

model = pickle.load(open('model1.pkl', 'rb'))