# -*- coding: utf-8 -*-
"""2nd Model - Decision_Tree.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tv8RApC_NwpNr9HDNUsyufsbETl0nZyc
"""

import pandas as pd
import pickle

df = pd.read_csv('Upscale - Sheet3.csv')

df = df.drop(columns="Hybridization REF")
from sklearn.model_selection import train_test_split
training_set, test_set = train_test_split(df, test_size = 0.3, random_state = 1)

X_train = training_set.iloc[:,0:3].values
Y_train = training_set.iloc[:,3].values

X_test = test_set.iloc[:,0:3].values
Y_test = test_set.iloc[:,3].values

from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier(max_depth = 10, random_state = 101, max_features = None, min_samples_leaf = 15)
dtree.fit(X_train, Y_train)

y_pred = dtree.predict(X_test)

from sklearn.metrics import accuracy_score
accuracy_score(Y_test,y_pred)

from sklearn.metrics import precision_score, recall_score, f1_score
precision = precision_score(Y_test,y_pred)
print(precision)

recall_score(Y_test, y_pred)

f1_score(Y_test, y_pred)

#serialization and de-serialization
pickle.dump(dtree, open('model.pkl','wb'))

model = pickle.load(open('model.pkl', 'rb'))